# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 21:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=12, unique=True)),
                ('source_exact', models.CharField(blank=True, max_length=255, verbose_name='E.g. table number, product name')),
                ('period', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, verbose_name='URL of the original source or a link to more technical notes.')),
                ('age_strat', models.CharField(blank=True, choices=[(None, ''), ('P', '0-4 years'), ('Q', '5-17 years'), ('R', '18-39 years'), ('S', '40-64 years'), ('T', '65 and older'), ('O', 'other')], max_length=1, verbose_name='age')),
                ('sex_strat', models.CharField(blank=True, choices=[(None, ''), ('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='sex')),
                ('race_strat', models.CharField(blank=True, choices=[(None, ''), ('W', 'Non-Hispanic White'), ('B', 'Non-Hispanic Black'), ('A', 'Asian'), ('H', 'Hispanic/Latino')], max_length=1, verbose_name='race/ethnicity')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('denominator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attributes.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Parent_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=12, unique=True)),
                ('name', models.CharField(max_length=127, unique=True)),
                ('units', models.CharField(blank=True, max_length=127)),
                ('category', models.CharField(blank=True, max_length=127)),
                ('technical_notes', models.TextField(blank=True, verbose_name='Detailed notes on how this attribute was collected or calculated.')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.Parent_Attribute'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attributes.Source'),
        ),
    ]
